language: android

android:
   components:
   - tools
   - platform-tools
   - android-29
   - build-tools-29.0.1
   - extra

jdk: oraclejdk7

notifications:
  email: false

before_install:
   - touch local.properties

script:
  - ./gradlew install
